defaults:
  - modules/encoder@encoder: rec_unet_enc
  - modules/decoder@decoder: rec_unet_dec

_target_: training.dlwp.model.models.unet.HEALPixRecUNet
_recursive_: false
presteps: 1
input_time_dim: ${data.input_time_dim}
output_time_dim: ${data.output_time_dim}
delta_time: ${data.time_step}

# Parameters automatically overridden in train code
input_channels: 7
output_channels: 7
n_constants: 2
decoder_input_channels: 1

# some perf parameters
enable_nhwc: false
enable_healpixpad: false