defaults:
  - criterion: mse
  - optimizer: adam
  - lr_scheduler: cosine

_target_: training.dlwp.trainer.trainer.Trainer
_recursive_: true
max_epochs: 50
min_epochs: 1
early_stopping_patience: null
amp_mode: "fp16"
graph_mode: "train_eval"
output_dir: ${output_dir}
